#!/bin/bash

set -ex

#use like this: ./testit_env <preset name>
#for example ./testit_env minSizeRel

pushd ../..
pipenv run ./build
popd
pipenv run pip install --force-reinstall ../../dist/leaninit*.whl
pipenv run ./testit $*